# Generated by Django 4.1.3 on 2022-11-21 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RecommendedMovie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('listed_in', models.CharField(max_length=100)),
                ('director', models.CharField(max_length=25)),
                ('release_year', models.IntegerField()),
                ('type', models.CharField(max_length=10)),
                ('description', models.CharField(max_length=500)),
                ('cast', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='SearchMovie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('release_year', models.IntegerField()),
                ('cast', models.CharField(max_length=100)),
                ('index', models.IntegerField()),
            ],
        ),
    ]
